sudo: required
services:
  - docker

before_install:
  - docker build -t maikonb/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true maikonb/react-test npm test

after_success:
  - docker build -t maikonb/multi-client  ./client
  - docker build -t maikonb/multi-nginx   ./nginx
  - docker build -t maikonb/multi-server  ./server
  - docker build -t maikonb/multi-worker  ./worker
  # Log in to the docker CLI (docker login com user/passw)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push maikonb/multi-client
  - docker push maikonb/multi-nginx
  - docker push maikonb/multi-server
  - docker push maikonb/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-940584446841
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    